name: universal_html_compat
version: 3.0.0
description:
  A universal_html that is WASM compatible. Provides its own implementations, and does not depend on 'dart:html'.

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  async: ^2.11.0
  csslib: '>=0.17.3 <2.0.0'
  charcode: ^1.2.0
  collection: ^1.17.1
  meta: ^1.9.1
  source_span: ^1.9.1
  typed_data: ^1.3.2
  universal_io: ^2.2.2

dev_dependencies:
  lints: ^2.1.0
  stream_channel: ^2.1.1
  test: ^1.24.3